[project]
name = "efficiency-nodes-ED"
description = "独立的 Efficiency Nodes ED 扩展：核心 Loader、LoRA Stack 与 XY 流程均由本插件提供；Impact、SUPIR、TIPO 等高级能力仅作为可选适配。"
version = "0.9.7"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/NyaamZ/efficiency-nodes-ED"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "nyaamz"
DisplayName = "efficiency-nodes-ED"
Icon = "https://upload.wikimedia.org/wikipedia/commons/d/d5/Speech_balloon_green_icon.svg"
